// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package fixture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadFixture returns the embedded CollectionSpec for Fixture.
func LoadFixture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FixtureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Fixture: %w", err)
	}

	return spec, err
}

// LoadFixtureObjects loads Fixture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FixtureObjects
//	*FixturePrograms
//	*FixtureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFixtureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFixture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FixtureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FixtureSpecs struct {
	FixtureProgramSpecs
	FixtureMapSpecs
	FixtureVariableSpecs
}

// FixtureProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FixtureProgramSpecs struct {
	EmitFixture *ebpf.ProgramSpec `ebpf:"emit_fixture"`
}

// FixtureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FixtureMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// FixtureVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FixtureVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// FixtureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFixtureObjects or ebpf.CollectionSpec.LoadAndAssign.
type FixtureObjects struct {
	FixturePrograms
	FixtureMaps
	FixtureVariables
}

func (o *FixtureObjects) Close() error {
	return _FixtureClose(
		&o.FixturePrograms,
		&o.FixtureMaps,
	)
}

// FixtureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFixtureObjects or ebpf.CollectionSpec.LoadAndAssign.
type FixtureMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *FixtureMaps) Close() error {
	return _FixtureClose(
		m.Events,
	)
}

// FixtureVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFixtureObjects or ebpf.CollectionSpec.LoadAndAssign.
type FixtureVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// FixturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFixtureObjects or ebpf.CollectionSpec.LoadAndAssign.
type FixturePrograms struct {
	EmitFixture *ebpf.Program `ebpf:"emit_fixture"`
}

func (p *FixturePrograms) Close() error {
	return _FixtureClose(
		p.EmitFixture,
	)
}

func _FixtureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fixture_bpfel.o
var _FixtureBytes []byte
