// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TinytapKprobeSendfileSample struct {
	_          structs.HostLayout
	PayloadLen uint32
	Payload    [4096]uint8
}

// LoadTinytapKprobe returns the embedded CollectionSpec for TinytapKprobe.
func LoadTinytapKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TinytapKprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TinytapKprobe: %w", err)
	}

	return spec, err
}

// LoadTinytapKprobeObjects loads TinytapKprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TinytapKprobeObjects
//	*TinytapKprobePrograms
//	*TinytapKprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTinytapKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTinytapKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TinytapKprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapKprobeSpecs struct {
	TinytapKprobeProgramSpecs
	TinytapKprobeMapSpecs
	TinytapKprobeVariableSpecs
}

// TinytapKprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapKprobeProgramSpecs struct {
	HandleTcpSendmsgLocked *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg_locked"`
}

// TinytapKprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapKprobeMapSpecs struct {
	SendfileSampleMap  *ebpf.MapSpec `ebpf:"sendfile_sample_map"`
	SendfileScratchMap *ebpf.MapSpec `ebpf:"sendfile_scratch_map"`
}

// TinytapKprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapKprobeVariableSpecs struct {
}

// TinytapKprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapKprobeObjects struct {
	TinytapKprobePrograms
	TinytapKprobeMaps
	TinytapKprobeVariables
}

func (o *TinytapKprobeObjects) Close() error {
	return _TinytapKprobeClose(
		&o.TinytapKprobePrograms,
		&o.TinytapKprobeMaps,
	)
}

// TinytapKprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapKprobeMaps struct {
	SendfileSampleMap  *ebpf.Map `ebpf:"sendfile_sample_map"`
	SendfileScratchMap *ebpf.Map `ebpf:"sendfile_scratch_map"`
}

func (m *TinytapKprobeMaps) Close() error {
	return _TinytapKprobeClose(
		m.SendfileSampleMap,
		m.SendfileScratchMap,
	)
}

// TinytapKprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapKprobeVariables struct {
}

// TinytapKprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapKprobePrograms struct {
	HandleTcpSendmsgLocked *ebpf.Program `ebpf:"handle_tcp_sendmsg_locked"`
}

func (p *TinytapKprobePrograms) Close() error {
	return _TinytapKprobeClose(
		p.HandleTcpSendmsgLocked,
	)
}

func _TinytapKprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tinytapkprobe_bpfeb.o
var _TinytapKprobeBytes []byte
