// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TinytapIncomingPending struct {
	_       structs.HostLayout
	Syscall uint32
	Fd      int32
	Buf     uint64
	Iovcnt  uint32
	Pad     uint32
}

type TinytapSendfileSample struct {
	_          structs.HostLayout
	PayloadLen uint32
	Payload    [4096]uint8
}

// LoadTinytap returns the embedded CollectionSpec for Tinytap.
func LoadTinytap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TinytapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tinytap: %w", err)
	}

	return spec, err
}

// LoadTinytapObjects loads Tinytap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TinytapObjects
//	*TinytapPrograms
//	*TinytapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTinytapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTinytap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TinytapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapSpecs struct {
	TinytapProgramSpecs
	TinytapMapSpecs
	TinytapVariableSpecs
}

// TinytapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapProgramSpecs struct {
	HandleAccept4      *ebpf.ProgramSpec `ebpf:"handle_accept4"`
	HandleClose        *ebpf.ProgramSpec `ebpf:"handle_close"`
	HandleExitRead     *ebpf.ProgramSpec `ebpf:"handle_exit_read"`
	HandleExitReadv    *ebpf.ProgramSpec `ebpf:"handle_exit_readv"`
	HandleExitRecvfrom *ebpf.ProgramSpec `ebpf:"handle_exit_recvfrom"`
	HandleExitRecvmsg  *ebpf.ProgramSpec `ebpf:"handle_exit_recvmsg"`
	HandleExitSendfile *ebpf.ProgramSpec `ebpf:"handle_exit_sendfile"`
	HandleRead         *ebpf.ProgramSpec `ebpf:"handle_read"`
	HandleReadv        *ebpf.ProgramSpec `ebpf:"handle_readv"`
	HandleRecvfrom     *ebpf.ProgramSpec `ebpf:"handle_recvfrom"`
	HandleRecvmsg      *ebpf.ProgramSpec `ebpf:"handle_recvmsg"`
	HandleSendfile     *ebpf.ProgramSpec `ebpf:"handle_sendfile"`
	HandleSendmsg      *ebpf.ProgramSpec `ebpf:"handle_sendmsg"`
	HandleSendto       *ebpf.ProgramSpec `ebpf:"handle_sendto"`
	HandleWrite        *ebpf.ProgramSpec `ebpf:"handle_write"`
	HandleWritev       *ebpf.ProgramSpec `ebpf:"handle_writev"`
}

// TinytapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapMapSpecs struct {
	Events             *ebpf.MapSpec `ebpf:"events"`
	IncomingPendingMap *ebpf.MapSpec `ebpf:"incoming_pending_map"`
	SendfileSampleMap  *ebpf.MapSpec `ebpf:"sendfile_sample_map"`
}

// TinytapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapVariableSpecs struct {
	OwnPid *ebpf.VariableSpec `ebpf:"own_pid"`
}

// TinytapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapObjects struct {
	TinytapPrograms
	TinytapMaps
	TinytapVariables
}

func (o *TinytapObjects) Close() error {
	return _TinytapClose(
		&o.TinytapPrograms,
		&o.TinytapMaps,
	)
}

// TinytapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapMaps struct {
	Events             *ebpf.Map `ebpf:"events"`
	IncomingPendingMap *ebpf.Map `ebpf:"incoming_pending_map"`
	SendfileSampleMap  *ebpf.Map `ebpf:"sendfile_sample_map"`
}

func (m *TinytapMaps) Close() error {
	return _TinytapClose(
		m.Events,
		m.IncomingPendingMap,
		m.SendfileSampleMap,
	)
}

// TinytapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapVariables struct {
	OwnPid *ebpf.Variable `ebpf:"own_pid"`
}

// TinytapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapPrograms struct {
	HandleAccept4      *ebpf.Program `ebpf:"handle_accept4"`
	HandleClose        *ebpf.Program `ebpf:"handle_close"`
	HandleExitRead     *ebpf.Program `ebpf:"handle_exit_read"`
	HandleExitReadv    *ebpf.Program `ebpf:"handle_exit_readv"`
	HandleExitRecvfrom *ebpf.Program `ebpf:"handle_exit_recvfrom"`
	HandleExitRecvmsg  *ebpf.Program `ebpf:"handle_exit_recvmsg"`
	HandleExitSendfile *ebpf.Program `ebpf:"handle_exit_sendfile"`
	HandleRead         *ebpf.Program `ebpf:"handle_read"`
	HandleReadv        *ebpf.Program `ebpf:"handle_readv"`
	HandleRecvfrom     *ebpf.Program `ebpf:"handle_recvfrom"`
	HandleRecvmsg      *ebpf.Program `ebpf:"handle_recvmsg"`
	HandleSendfile     *ebpf.Program `ebpf:"handle_sendfile"`
	HandleSendmsg      *ebpf.Program `ebpf:"handle_sendmsg"`
	HandleSendto       *ebpf.Program `ebpf:"handle_sendto"`
	HandleWrite        *ebpf.Program `ebpf:"handle_write"`
	HandleWritev       *ebpf.Program `ebpf:"handle_writev"`
}

func (p *TinytapPrograms) Close() error {
	return _TinytapClose(
		p.HandleAccept4,
		p.HandleClose,
		p.HandleExitRead,
		p.HandleExitReadv,
		p.HandleExitRecvfrom,
		p.HandleExitRecvmsg,
		p.HandleExitSendfile,
		p.HandleRead,
		p.HandleReadv,
		p.HandleRecvfrom,
		p.HandleRecvmsg,
		p.HandleSendfile,
		p.HandleSendmsg,
		p.HandleSendto,
		p.HandleWrite,
		p.HandleWritev,
	)
}

func _TinytapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tinytap_bpfeb.o
var _TinytapBytes []byte
