// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TinytapUprobeSslFdKey struct {
	_   structs.HostLayout
	Pid uint32
	Pad uint32
	Ssl uint64
}

// LoadTinytapUprobe returns the embedded CollectionSpec for TinytapUprobe.
func LoadTinytapUprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TinytapUprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TinytapUprobe: %w", err)
	}

	return spec, err
}

// LoadTinytapUprobeObjects loads TinytapUprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TinytapUprobeObjects
//	*TinytapUprobePrograms
//	*TinytapUprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTinytapUprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTinytapUprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TinytapUprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapUprobeSpecs struct {
	TinytapUprobeProgramSpecs
	TinytapUprobeMapSpecs
	TinytapUprobeVariableSpecs
}

// TinytapUprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapUprobeProgramSpecs struct {
	HandleSslSetFd *ebpf.ProgramSpec `ebpf:"handle_ssl_set_fd"`
}

// TinytapUprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapUprobeMapSpecs struct {
	SslFdMap *ebpf.MapSpec `ebpf:"ssl_fd_map"`
}

// TinytapUprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapUprobeVariableSpecs struct {
}

// TinytapUprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapUprobeObjects struct {
	TinytapUprobePrograms
	TinytapUprobeMaps
	TinytapUprobeVariables
}

func (o *TinytapUprobeObjects) Close() error {
	return _TinytapUprobeClose(
		&o.TinytapUprobePrograms,
		&o.TinytapUprobeMaps,
	)
}

// TinytapUprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapUprobeMaps struct {
	SslFdMap *ebpf.Map `ebpf:"ssl_fd_map"`
}

func (m *TinytapUprobeMaps) Close() error {
	return _TinytapUprobeClose(
		m.SslFdMap,
	)
}

// TinytapUprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapUprobeVariables struct {
}

// TinytapUprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapUprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapUprobePrograms struct {
	HandleSslSetFd *ebpf.Program `ebpf:"handle_ssl_set_fd"`
}

func (p *TinytapUprobePrograms) Close() error {
	return _TinytapUprobeClose(
		p.HandleSslSetFd,
	)
}

func _TinytapUprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tinytapuprobe_arm64_bpfel.o
var _TinytapUprobeBytes []byte
