// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTinytap returns the embedded CollectionSpec for Tinytap.
func LoadTinytap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TinytapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tinytap: %w", err)
	}

	return spec, err
}

// LoadTinytapObjects loads Tinytap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TinytapObjects
//	*TinytapPrograms
//	*TinytapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTinytapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTinytap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TinytapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapSpecs struct {
	TinytapProgramSpecs
	TinytapMapSpecs
	TinytapVariableSpecs
}

// TinytapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapProgramSpecs struct {
}

// TinytapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapMapSpecs struct {
}

// TinytapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TinytapVariableSpecs struct {
}

// TinytapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapObjects struct {
	TinytapPrograms
	TinytapMaps
	TinytapVariables
}

func (o *TinytapObjects) Close() error {
	return _TinytapClose(
		&o.TinytapPrograms,
		&o.TinytapMaps,
	)
}

// TinytapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapMaps struct {
}

func (m *TinytapMaps) Close() error {
	return _TinytapClose()
}

// TinytapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapVariables struct {
}

// TinytapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTinytapObjects or ebpf.CollectionSpec.LoadAndAssign.
type TinytapPrograms struct {
}

func (p *TinytapPrograms) Close() error {
	return _TinytapClose()
}

func _TinytapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tinytap_bpfeb.o
var _TinytapBytes []byte
