name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -coverprofile=coverage.out ./internal/protocols/http/... ./internal/output/tui/...

      - uses: codecov/codecov-action@v5
        with:
          files: coverage.out
